const INPUT_NODE_NAMES = ['SELECT', 'INPUT', 'TEXTAREA', 'BUTTON']

/**
 * Keyboard event handler that will trap keypresses that don't occur in either form elements or
 * when Babylon objects have focus.
 *
 * Also takes care of removing focus from a Bablyon object on pointerlock change.
 */
export interface KeyboardEventHandler {
  // `key` is the value of the key pressed by the user, taking into consideration the state of modifier keys
  // such as Shift as well as the keyboard locale and layout.
  // https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
  key?: string

  // `code` represents a physical key on the keyboard (as opposed to the character generated by
  // pressing the key). In other words, this property returns a value that isn't altered
  // by keyboard layout or the state of the modifier keys.
  // https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
  code?: string

  // filter by modifier keys (must be used with `key` or `code`)
  ctrlKey?: boolean
  shiftKey?: boolean
  metaKey?: boolean

  // https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#keyboard_locations
  location?: number

  handleEvent: (event: KeyboardEvent) => void
}

interface KeyboardHandlerOptions {
  keyDown?: Array<KeyboardEventHandler>
  keyUp?: Array<KeyboardEventHandler>
  keyHeld?: Array<KeyboardEventHandler>
}

export class KeyboardHandler {
  scene: BABYLON.Scene
  keyDownHandlers: Set<KeyboardEventHandler> = new Set()
  keyUpHandlers: Set<KeyboardEventHandler> = new Set()
  keyHeldHandlers: Set<KeyboardEventHandler> = new Set()

  constructor(scene: BABYLON.Scene, options?: KeyboardHandlerOptions) {
    document.addEventListener('keydown', this.onKeyDown)
    document.addEventListener('keyup', this.onKeyUp)
    document.addEventListener('pointerlockchange', this.onPointerLockChange)

    this.scene = scene
    options?.keyDown?.forEach((handler) => this.addKeyDown(handler))
    options?.keyUp?.forEach((handler) => this.addKeyUp(handler))
    options?.keyHeld?.forEach((handler) => this.addKeyDown(handler))
  }

  dispose() {
    document.removeEventListener('keydown', this.onKeyDown)
    document.removeEventListener('keyup', this.onKeyUp)
    document.removeEventListener('pointerlockchange', this.onPointerLockChange)
  }

  onKeyDown = (event: KeyboardEvent) => {
    if (this._isLocked) {
      // Prevent browser shortcuts when pointer is locked
      if (event.ctrlKey || event.metaKey) {
        // allow refresh
        if (event.key !== 'r') {
          event.preventDefault()
          event.stopPropagation()
        }
        return
      }
    }
    if (event.repeat) {
      this.keyHeldHandlers.forEach((handler) => {
        if (checkHandlerForEvent(handler, event)) {
          handler.handleEvent(event)
        }
      })
    } else if (!isInput(event!.target!) && !this.getBabylonControlHasFocus()) {
      this.keyDownHandlers.forEach((handler) => {
        if (checkHandlerForEvent(handler, event)) {
          handler.handleEvent(event)
        }
      })
    }
  }

  onKeyUp = (event: KeyboardEvent) => {
    if (!isInput(event!.target!) && !this.getBabylonControlHasFocus()) {
      this.keyUpHandlers.forEach((handler) => {
        if (checkHandlerForEvent(handler, event)) {
          handler.handleEvent(event)
        }
      })
    }
  }

  private _isLocked = false
  onPointerLockChange = () => {
    const hasLocked = !!document.pointerLockElement
    this._isLocked = hasLocked
    this.clearBabylonControlFocus()
  }

  addKeyDown(eventHandler: KeyboardEventHandler) {
    this.keyDownHandlers.add(eventHandler)
    return eventHandler
  }

  removeKeyDown(eventHandler: KeyboardEventHandler) {
    this.keyDownHandlers.add(eventHandler)
  }

  addKeyUp(eventHandler: KeyboardEventHandler) {
    this.keyUpHandlers.add(eventHandler)
    return eventHandler
  }

  removeKeyUp(eventHandler: KeyboardEventHandler) {
    this.keyUpHandlers.add(eventHandler)
  }

  clearBabylonControlFocus() {
    this.scene.textures.forEach((texture) => {
      if (texture instanceof BABYLON.GUI.AdvancedDynamicTexture) {
        texture.focusedControl = null
      }
    })
  }

  getBabylonControlHasFocus() {
    // find out if a text input or similar has keyboard focus
    return this.scene.textures.some((texture) => {
      if (texture instanceof BABYLON.GUI.AdvancedDynamicTexture) {
        return !!texture.focusedControl
      }
    })
  }
}

function checkHandlerForEvent(handler: KeyboardEventHandler, event: KeyboardEvent) {
  // if not modifier keys not specified, ignore shortcuts with modifier keys pressed
  if (!('metaKey' in handler) && event.metaKey) return
  if (!('ctrlKey' in handler) && event.ctrlKey) return

  // scan through to see if our handler matches the event
  for (const key in handler) {
    if (key !== 'handleEvent') {
      if ((event as any)[key] !== (handler as any)[key]) {
        return false
      }
    }
  }
  return true
}

function isInput(element: EventTarget) {
  if (element instanceof HTMLElement) {
    return INPUT_NODE_NAMES.includes(element.nodeName)
  } else {
    return false
  }
}
