export { createLightmapMaterial } from '../shaders/lightmap'
export { createVoxelMaterial } from '../shaders/voxel'
export { clearCache, getCacheStats, isShared } from './cache'
export { toColor3, type ColorInput } from './color-utils'
export { createGlassMaterial, type GlassConfig } from './glass'
export { createIslandMaterial, type IslandMaterialConfig } from './island'
export { createLanternMaterial, type LanternMaterialConfig } from './lantern'
